[package]
name = "dumper"
version = "0.1.0"
authors = ["Philpax <me@philpax.me>"]
edition = "2018"

[dependencies]
bzip2 = { git = "https://github.com/alexcrichton/bzip2-rs" }
rayon = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
roxmltree = "0.13.0"